services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - NUXT_PUBLIC_API_BASE=http://localhost:${BACKEND_PORT}/api
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
    
  backend:
    volumes:
      - ./backend:/var/www/html
      - /var/www/html/vendor
      - /var/www/html/storage
      - backend_storage:/var/www/html/storage
      - backend_bootstrap_cache:/var/www/html/bootstrap/cache
    environment:
      - APP_ENV=local
      - APP_DEBUG=true