name: 融資貸款CRM系統 - 持續部署

on:
  push:
    branches: [ master, develop ]

jobs:
  deploy-production:
    name: 部署到生產環境
    runs-on: ubuntu-latest
    environment: production
    
    steps:
      - name: 取出程式碼
        uses: actions/checkout@v4

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -p 8022 -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy via SSH
        run: |
          ssh -p 8022 -i ~/.ssh/id_ed25519 -o ServerAliveInterval=60 -o ServerAliveCountMax=3 ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd ~/project/bonus/finance
            git pull
            docker compose up -d --build frontend
            docker compose exec backend php artisan migrate --force
          EOF